blank_issues_enabled: false
contact_links:
  - name: Read CONTRIBUTING first
    url: https://github.com/rozdolsky33/ocloud/blob/main/CONTRIBUTING.md
    about: Please review our contributing guide (architecture, how to run, how to file a good issue) before opening a new issue.
  - name: Questions and Support
    url: https://github.com/rozdolsky33/ocloud/discussions
    about: If you have a question rather than a bug or feature request, please use Discussions.