# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocloud < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/rozdolsky33/ocloud"
  version "0.0.29"
  license "MIT"

  on_macos do
    url "https://github.com/rozdolsky33/ocloud/releases/download/v0.0.29/ocloud_0.0.29_darwin_all.tar.gz"
    sha256 "c3650949ddb67b483af96eb1ea345f71d43748c29cc4599b226a4f966215605e"

    def install
      bin.install "ocloud"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rozdolsky33/ocloud/releases/download/v0.0.29/ocloud_0.0.29_linux_amd64.tar.gz"
      sha256 "29265dfe5bfebea4927546c6d909724de08f2e67314d49096020c603c7e3eea5"
      def install
        bin.install "ocloud"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rozdolsky33/ocloud/releases/download/v0.0.29/ocloud_0.0.29_linux_arm64.tar.gz"
      sha256 "7b2705112a7e962730b2eeed76f26e0cf789e627a956f644b31f04f66291323b"
      def install
        bin.install "ocloud"
      end
    end
  end
end
