# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocloud < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/rozdolsky33/ocloud"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/rozdolsky33/ocloud/releases/download/v0.1.1/ocloud_0.1.1_darwin_all.tar.gz"
    sha256 "68c0a26fe74b1a9891f7bbcd66eee660ac1085a66fa3dc4861d88d3cf9a8ea85"

    def install
      bin.install "ocloud"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rozdolsky33/ocloud/releases/download/v0.1.1/ocloud_0.1.1_linux_amd64.tar.gz"
      sha256 "477b98fbb1e09fb911bce6a16f08d7b9d40f15f53a76c3498007e2bd895b4faa"
      def install
        bin.install "ocloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rozdolsky33/ocloud/releases/download/v0.1.1/ocloud_0.1.1_linux_arm64.tar.gz"
      sha256 "bf29230c9ed68b4c9422622726544a09b1d2b040a0e5a48b3cd40fa0381c593c"
      def install
        bin.install "ocloud"
      end
    end
  end
end
