name: CI Build

on:
  push:
    branches:
      - "main"
      - 'feature-*'
      - 'feature/*'
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Run go vet
        run: go vet ./...


      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: true
          chart: true
          amend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPORT_COV }}
        continue-on-error: true

      - name: Build project
        run: |
          make clean
          make test
          make build
