name: Enforce Merging from Develop Only

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-branch-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from 'develop' branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ PR to main is only allowed from develop."
            exit 1
          else
            echo "✅ Merge allowed."
          fi